site_name: VietKidsNZ-Coding Club
site_description: Training materials and info about the Club activities
site_author: Trung Truong
#theme: readthedocs
theme:
  name: material

markdown_extensions:
  - toc
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.emoji
nav:
  - Home: index.md
  - Our Projects: projects.md
  - Scratch: scratch.md
  - About: about.md