site_name: VietKidsNZ-Coding Club
site_description: Training materials and info about the Club activities
site_author: Trung Truong
theme: readthedocs
nav:
  - Home: index.md
  - Our meetup: meetup.md
  - Our Projects: projects.md
  - Scratch: scratch.md
  - About: about.md